Feature/1
wlsh44/calculator pull request #2
Opened 2022-02-18 13:30 UTC by wlsh44

예외처리 없이 기본적이 사칙연산 기능만 동작하는 부분까지 구현해서 pr 합니다!

2022-02-19 14:32 UTC, f-lab-mammouth commented on build.gradle
> +    testImplementation 'org.assertj:assertj-core:3.22.0'
@wlsh44 assertj 추가 하신 이유가 뭔지 알수 있을까요?

2022-02-19 14:36 UTC, f-lab-mammouth commented on src/main/java/Application.java
> +public class Application {
@wlsh44 어떤 생각에서 바꾸신건지 궁금해요 :)

2022-02-20 12:40 UTC, f-lab-mammouth commented on src/main/java/Calculator/InputHandlerImpl.java
> +public class InputHandlerImpl implements InputHandler {
@wlsh44 
`InputHandlerImpl` 보다 좀 더 직관적인 클래스명을 생각해보면 좋을거 같아요.
보통 spring 프로젝트에서 `interface`의 구현체에 `impl` 을 사용하곤 하는데요.
만약 나중에 또 다른 구현체를 만들때는 그럼 `impl2`를 사용해야 할까요?

클래스명만 봐도 어떤 구현체인지 알수있게 이름을 지으면 좋을거 같습니다.

2022-02-20 12:43 UTC, f-lab-mammouth commented on src/main/java/Calculator/InputHandlerImpl.java
> +        Scanner scanner = new Scanner(System.in);
@wlsh44 
`inputData()` 메서드가 실행될때마다 `Scanner`  객체를 생성해야 할까요?

2022-02-20 12:48 UTC, f-lab-mammouth commented on src/main/java/Calculator/Calculator.java
> +    }
@wlsh44 
`calculate()` 라는 메서드명은 `계산` 에 대한 책임을 갖을것 같은데요.
요 메서드는 지금 `사용자로부터의 입력`을 받는 책임과 `계산`을 하는 책임 두가지를 가지고 있어요.

메서드를 분리하는게 어떨까요?

2022-02-20 12:50 UTC, f-lab-mammouth commented on src/main/java/Application.java
> +
`main` 메서드에서는 `Calculator`를 직접 사용하는 코드를 작성하면 좋을거 같아요 :)

2022-02-20 12:52 UTC, f-lab-mammouth commented on src/main/java/Calculator/CalculateHandlerImpl.java
> +    }
@wlsh44 
`isDigit` 과 같은 메서드가 `CalculateHandlerImpl` 의 메서드로 존재하는게 좋을까요?
- 추후 확장성을 고려해보면 좋을거 같아요.

2022-02-20 12:54 UTC, f-lab-mammouth commented on src/main/java/Calculator/Calculator.java
> +
@wlsh44 
위 변수들이 추후 바뀔 가능성이 있을까요? 혹은 `immutable` 해야하는 변수일까요?
만약 `immutable` 해야하는 변수라면 `final` 키워드를 추가해주는게 좋을거 같아요 :)

2022-02-20 12:58 UTC, f-lab-mammouth commented on src/main/java/Calculator/CalculateHandlerImpl.java
> +            }
`switch` 문의 단점은 뭐가 있을까요? 
좀 더 `객체지향적` 으로 코드를 짤수 있는 방법이 있지 않을까요?

`객체지향적` 이라는 단어가 굉장히 많은 의미를 담고 있긴 하지만,
가장 기본이 되는 한가지는 `연관이 있는 속성과 행동들을 하나의 객체에 묶는다` 라는 건데요.

만약 `Operator` 클래스에 다른 상수가 추가되거나, 기존 상수가 삭제되면 `Operator` 클래스뿐 아니라 `CalculateHandlerImpl` 클래스도 수정을 해줘야 하는 상황입니다.

어떻게 하면 좀 더 효율적인 코드가 될수 있을까요? :)

2022-02-20 13:01 UTC, f-lab-mammouth commented on src/main/java/Calculator/CalculateHandlerImpl.java
> +    }
@wlsh44 
리턴 타입이 `void` 인 메서드는 테스트하기가 어렵습니다.
메서드가 `numIter` 와 `operatorIter`에 강하게 의존하고 있는데요.
의존적이지 않은 메서드, 테스트하기 좋은 메서드로 바꿀수 있는 방법은 없을까요?

2022-02-20 13:06 UTC, f-lab-mammouth commented on src/test/java/SampleTest.java
> +}
@wlsh44 
가능하면 모든 메서드들에 대해 테스트코드를 작성하길 추천드립니다 :) 
그리고, 각 테스트는 기존 `클래스명 + Test` 로 파일명을 지어서 생성하는게 좋습니다 :) 

ex) `InputHandlerTest`

2022-02-20 13:08 UTC, f-lab-mammouth requested changes
@wlsh44 
코드 짜시느라 수고하셨어요 :) 

피드백을 많이 드렸는데요. 
각각의 피드백에 대해 한번 깊이 고민해보고 여러방면으로 풀어나가 보시면 좋을거 같아요 :)

2022-02-21 14:31 UTC, wlsh44 commented on build.gradle
> +    testImplementation 'org.assertj:assertj-core:3.22.0'
assertj에 있는 assertThat의 사용을 위해 추가하였습니다. junit에 있는 테스트 메서드들은 assertEquals 처럼 메서드 이름 자체에 원하는 결과가 포함되어있어 인자로 결과값과 기대값을 둘 다 넣어줘야 합니다. 하지만 이렇게 될 경우 간혹 어떤 위치에 어떤 값이 들어가야 하는지 헷갈릴 수도 있고 가독성 측면에서 떨어지게 됩니다. assertThat을 사용할 경우 조금 더 문장과 비슷한 테스트 코드가 되어 더 가독성이 좋은 코드가 작성이 되기 때문에 assertj를 추가하였습니다.

2022-02-21 14:32 UTC, wlsh44 commented on src/main/java/Calculator/InputHandlerImpl.java
> +public class InputHandlerImpl implements InputHandler {
요구사항 반영하여
InputHandlerImpl -> SystemInputHandler
CalculateHandlerImpl -> ArithmeticCalculateHandler
로 이름 변경하였습니다.

2022-02-21 14:33 UTC, wlsh44 commented on src/main/java/Calculator/InputHandlerImpl.java
> +        Scanner scanner = new Scanner(System.in);
매서드 실행 될 때마다 Scanner 객체가 생성되지 않게 맴버 변수로 변경하여 한 번만 초기화 되도록 하였습니다.

2022-02-21 14:33 UTC, wlsh44 commented on src/main/java/Calculator/Calculator.java
> +    }
입력 부분, 계산 부분으로 메서드를 분리하였습니다.

2022-02-21 14:34 UTC, wlsh44 commented on src/main/java/Application.java
> +
추가하였습니다!

2022-02-21 14:38 UTC, wlsh44 commented on src/main/java/Calculator/CalculateHandlerImpl.java
> +    }
util class를 만들어 분리했습니다.
이 메서드를 사용할 때 클래스의 인스턴스 생성까지 필요 없다고 판단하여 static 메서드로 만들었습니다.

2022-02-21 14:39 UTC, wlsh44 commented on src/main/java/Calculator/Calculator.java
> +
두 Handler 변수들은 imutable하다고 판단하여 final 키워드 추가했습니다.

2022-02-21 14:52 UTC, wlsh44 commented on src/main/java/Calculator/CalculateHandlerImpl.java
> +            }
찾아본 결과, switch문은 어셈블리어로 바뀔 때 jump 연산을 하고 if 는 branch 연산을 한다고 합니다. jump는 점프테이블을 만들어 그 위치로 바로 이동하는 반면 if 는 branch를 이용해 조건을 연산하여 이동하기 때문에 조건의 수에 따라 수행 속도가 달라집니다. 그래서 이 코드 같은 경우는 조건이 적기 때문에 if 문으로 변경을 하였습니다.
하지만 가독성 측면에서 switch가 조금 더 낫다는 생각이 들기도 해서 어떤 경우에 switch, if 를 쓰는지 궁금증이 생겼습니다.

예시를 들어주셔서 조금 이해가 되었던 것 같습니다. 연산의 가장 기본은 연산자 하나와 피연산자 두 개로 이루어진다고 생각하여 CalculateHandler는 그 연산들의 최종 결과를 책임지고, 각각의 기본 연산은 Operator 가 책임을 져, 연산자가 추가되거나 해도 CalculateHandler에는 영향을 가지 않도록 수정을 해봤습니다.

2022-02-21 14:57 UTC, wlsh44 commented on src/main/java/Calculator/CalculateHandlerImpl.java
> +    }
가장 많이 고민을 했고 제대로 답이 나오지 않은 부분인 것 같습니다. 메서드가 맴버 변수를 사용하는 것이 의존적이게 되는 것에 대해 처음 생각해 본 것 같습니다. 우선은 각각 새로운 객체를 return 하는 메서드로 분리해서 테스트는 가능할 수 있도록 했지만 한 번에 할 수 있는 동작을 두 번 하는 것처럼 되어버려 비효율적이게 된 것 같습니다..

2022-02-21 14:57 UTC, wlsh44 commented on src/test/java/SampleTest.java
> +}
테스트 클래스 명 수정했습니다!

2022-02-22 07:35 UTC, f-lab-mammouth commented on src/main/java/Application.java
> +        System.out.println(calculator.calculate());
@wlsh44 
`InputHandler` 처럼 `Output`에 대한 책임을 갖는 `객체`를 만드는건 어떨까요?
현재처럼 `System.out.println`으로 썼을때와 `객체`로 만들었을때의 차이점은 무엇이 있을까요?

2022-02-22 07:39 UTC, f-lab-mammouth commented on src/main/java/Calculator/ArithmeticCalculateHandler.java
> +    private Deque<String> operatorIter;
@wlsh44 
이전 수업시간에 요 부분에 대해 질문을 드렸었는데요.
`이 클래스가 Deque에 강하게 의존을 하고 있는데 의존을 없애기 위해서 할수있는 방법이 무엇일까요?` 라는 질문이었습니다.
혹시 생각해보셨나요? :) 

그때 답변하셨던건 `Deque`의 부모 클래스나 인터페이스로 바꾸는걸 말씀하셨는데.
그보다 좀 더 `객체지향적인` 방식이 있을것 같습니다.

이 부분에 대해서는 지금 바로 답을 알려드리기 보다는 좀 더 생각해보시고 검색도 해보시는걸 추천드립니다 :)

2022-02-22 07:40 UTC, f-lab-mammouth commented on src/main/java/Calculator/CalculateUtil.java
> +}
@wlsh44 
👍

2022-02-22 07:45 UTC, f-lab-mammouth commented on src/main/java/Calculator/Operator.java
> +    }
@wlsh44 
👍
`Operator` 객체에 속성과 행동이 모두 모이도록 수정해주셨네요. 
이제 수정이 필요할때 이 클래스만 신경써도 될거 같은데요.
조금 더 `객체지향적인` 코드로 바꿀수 있을거 같아요.

`if-else`는 그 양이 늘어날수록 가독성이 좋지 않고 실수할 가능성도 늘어납니다.
`PLUS` 상수는 `plus` 메서드와 매칭되고, `MINUS` 상수는 `minus` 메서드와 매칭되고 있죠 :) 
그럼 매칭되는 녀석들끼리 `객체`로 만들수 있지 않을까요?
객체를 `runtime`에 선택적으로 실행되게 하려면 필요한 `자바의 특징`이 뭘까요? :)

2022-02-22 07:45 UTC, f-lab-mammouth commented on src/main/java/Calculator/SystemInputHandler.java
> +}
👍

2022-02-22 07:46 UTC, f-lab-mammouth commented on src/test/java/CalculateHandlerTest.java
> +    }
@wlsh44 
`@DisplayName` 이라는 어노테이션에 대해 검색해보시고 한번 사용해보세요 :)

2022-02-22 07:46 UTC, f-lab-mammouth commented on src/test/java/SampleTest.java
> +}
@wlsh44 
필요없는 클래스는 지워주세요 :)

2022-02-22 15:18 UTC, wlsh44 commented on src/main/java/Application.java
> +        System.out.println(calculator.calculate());
Output의 책임을 갖는 객체를 추가했습니다.
추후에 output의 형식에 대한 변화가 생기거나 System.out.println이 아닌 다른 방식으로 출력을 하는 데에 있어서 더 유연한 대처가 가능할 수 있을 것 같습니다. 또한 출력이 필요한 곳마다 구현을 하는 것이 아닌 한 번의 구현으로 재사용이 가능하여 더 수월한 개발이 가능하다는 차이가 있다고 생각합니다..!

2022-02-22 15:21 UTC, wlsh44 commented on src/main/java/Calculator/ArithmeticCalculateHandler.java
> +    private Deque<String> operatorIter;
이 부분에서 고민을 많이 했고 iterator에 대한 책임을 갖는 객체를 의존성 주입 하는 방식으로 변경을 해봤습니다. 
다만 뭔가 후련하게 해결한 느낌이 아니라 조금 더 고민이 필요한 것 같습니다..ㅠ

2022-02-22 15:25 UTC, f-lab-mammouth commented on src/main/java/Application.java
> +        calculator.printResult();
메서드가 각각의 책임을 갖게 된거 같네요! 👍

2022-02-22 15:26 UTC, f-lab-mammouth commented on src/main/java/Calculator/Calculator.java
> +    }
@wlsh44 
`return type`이 `void` 면 테스트가 힘들어요~
요 메서드도 수정하기 전에 테스트 케이스 한번 만들어 보시죠!

2022-02-22 15:29 UTC, f-lab-mammouth commented on src/main/java/Calculator/handler/calculate/DequeExpressionIterator.java
> +}
@wlsh44 
오우예!!!!
잘하셨습니다!!! 이거에요!!
이걸 `wrapper class` 라고 부릅니다.
요고 블로깅 하나 하시죠 :)
잘하셨어요~

2022-02-22 15:32 UTC, f-lab-mammouth commented on src/main/java/Calculator/operator/operators/Plus.java
> +}
@wlsh44 
잘 하셨어요 👍  훌륭합니다.
각각을 `interface`를 중심으로 `각각의 객체`로 만드는 방법도 있지만,
이렇게 각 객체가 하나의 메서드를 갖는 경우는 `Enum`을 사용 하는 방법이 더 효율적입니다.

조금 귀찮긴 하겠지만 아래 내용들에 대해 수정하고 알아봐주세요.
- `Enum` 을 사용하도록 수정
- `Enum` 의 장점

2022-02-22 15:34 UTC, f-lab-mammouth commented on src/test/java/CalculateHandlerTest.java
> +}
@wlsh44 
면접에서 중요하게 생각하는 것중 하나가 `Test` 작성입니다.
추후에 `Test` 작성에 대한 실습을 하겠지만,
미리 해보는것도 좋을것 같습니다 :) 

아래 내용들 해보시면 좋을것 같아요!
- 모든 `method`에 대해서 테스트 케이스를 작성해보세요.
- 특히 `void`로 된 케이스를 최대한 테스트 케이스로 작성해보세요.

2022-02-22 15:43 UTC, wlsh44 commented on src/main/java/Calculator/Operator.java
> +    }
Operator객체는 두 피연산자와 연산자 하나의 연산이라는 책임만 갖고 어떤 연산인지는 구현에 따라 달라진다고 생각을 하였습니다.
그래서 마지막 질문의 답이라고 생각되는 다형성으로 입력시에 결정되는 연산자로 연산을 구현하도록 Operator 객체를 추상화 하였습니다.

다만 if-else 또는 switch를 줄이는 방법에 대해서 enum 의 사용으로 접근을 해봤으나 잘 되지 않아서 보류하고 있습니다..ㅠ

2022-02-22 15:46 UTC, f-lab-mammouth commented on src/main/java/Calculator/Operator.java
> +    }
@wlsh44 
우선 `다형성`으로 잘 구현하셨어요 :) 
구현을 해보는것과 안해보는것은 차이가 큽니다. 

`Enum`에 대해서는 구글링을 해보면 좋은 자료가 많이 나옵니다.
한번 도전 해보시죠 !

2022-02-24 15:12 UTC, f-lab-mammouth commented on src/main/java/Application.java
> +        calculator.printResult();
@wlsh44 
저번 멘토링때 말씀 드렸던것처럼 외부에 제공하는 메서드와 외부에서 접근하지 못하는 메소드로 구분해보세요 :)

2022-02-24 15:13 UTC, f-lab-mammouth commented on src/main/java/Calculator/Calculator.java
> +    }
@wlsh44 
멘토링때 말씀 드렸던것처럼 멤버변수에 할당하는게 최선인지 한번 생각해보면 좋을거 같아요

2022-02-24 15:16 UTC, f-lab-mammouth commented on src/main/java/Calculator/Calculator.java
> +    }
@wlsh44 
조금 힌트를 더 드리자면 `Calculator`는 서비스로직을 가지고 있는 객체라면,
`데이터`와 관련된 것들은 따로 `객체`로 빼낼수 있지 않을까요?
`spring`으로 프로젝트를 하다보면 `dto`와 같은 느낌이라고 보시면 됩니다.

`wrapper 객체`라는 키워드로 한번 검색해보시고 생각해보시면 좋을듯 합니다 :)

2022-02-24 15:18 UTC, f-lab-mammouth commented on src/main/java/Calculator/handler/calculate/CalculateUtil.java
> +}
@wlsh44 
`Util` 성 클래스들은 패키지를 따로 만드는게 좀 더 관리하기 좋을거 같습니다.

2022-02-24 15:21 UTC, f-lab-mammouth commented on src/test/java/Calculator/CalculatorTest.java
> +        calculator = new Calculator(new SystemInputHandler(), new SystemOutputHandler(), new ArithmeticCalculateHandler(new DequeExpressionIterator()));
@wlsh44 
한줄에 이렇게 쭉 쓰는건 안티패턴이에요~
각각의 클래스를 생성할때 변수에 할당하고, 그 변수를 `new Calculator(변수1, 변수2, ...)` 와 같은식으로 수정하는게 좋을거 같습니다 :)

2022-02-24 15:23 UTC, f-lab-mammouth commented on src/test/java/Calculator/CalculatorTest.java
> +        calculator = new Calculator(new SystemInputHandler(), new SystemOutputHandler(), new ArithmeticCalculateHandler(new DequeExpressionIterator()));
@wlsh44 
그리고 모든 메서드에서 `initCalculator` 메서드를 먼저 호출하고 있는데,
이런 기능(초기화)을 하는 `@BeforeAll` 과 `@BeforeEach`에 대해 한번 찾아보세요 :)

2022-02-24 15:27 UTC, f-lab-mammouth commented on src/main/java/Calculator/operator/Operator.java
> +}
@wlsh44 
👍

2022-02-27 07:10 UTC, wlsh44 commented on src/main/java/Calculator/Calculator.java
> +    }
expression과 result를 dto로 분리해봤습니다. 
그런데 이런 경우에는 dto를 Calculator 내부, 외부 어디에서 관리해야 되는지에 대해 궁금증이 생겼습니다.

2022-02-27 07:15 UTC, wlsh44 commented on src/test/java/Calculator/CalculatorTest.java
> +        calculator = new Calculator(new SystemInputHandler(), new SystemOutputHandler(), new ArithmeticCalculateHandler(new DequeExpressionIterator()));
맨 처음에 @BeforeEach를 사용해 init을 하려고 했었는데 테스트마다 input 값이 바뀌어서 실패 했었습니다...ㅠ
혹시 @BeforeEach나 @BeforeAll을 사용할 때 값을 넣어주는 방법이 따로 있을까요??

2022-02-27 15:11 UTC, f-lab-mammouth commented on src/main/java/Calculator/Calculator.java
> +    }
@wlsh44 
`정답` 이란건 없습니다 :) 
반대로 누군가 진호님께 `dto`를 어디에 위치해야 하냐는 질문을 한다면 어떻게 대답하실건지 생각해보는것도 좋을것 같습니다.

저는 보통 코드를 짤때 두가지를 생각합니다.
1. 내가 이렇게 짰을때 누군가 질문을 한다면 상대방이 납득할만한 이유를 가지고 짠다.
2. 정말 아무리 생각해도 모르겠다면 `최대한 일반화된 코드` 를 참고한다.

제가 지금까지 봤을때 일반화된것은 `dto`를 진호님이 하신것처럼 외부에 `package`를 따로 만들어서 모아둡니다.
한번 오픈소스나 다른 사람들이 짠 소스코드를 찾아보면 좋을것 같네요.

2022-02-27 15:18 UTC, f-lab-mammouth commented on src/main/java/Calculator/Calculator.java
> +        dto.setExpression(inputHandler.inputData());
@wlsh44 
`dto.setExpression`을 `main` 메서드에서도 할수 있는것 같아요.
스프링에서도 `set` 메서드보다는 `생성자를 통한 주입`을 권장하는데요.
왜 `set` 메서드보다 `생성자를 통한 주입`을 권장하는지 한번 찾아보면 좋을것 같습니다.

1. `set` 메서드보다 `생성자를 통한 주입`을 권장하는 이유
2. 어떻게 하면 좀 더 `안전한` 코드로 리팩토링 가능할지

2022-02-27 15:23 UTC, f-lab-mammouth commented on src/main/java/Calculator/handler/IO/SystemOutputHandler.java
> +        String res = dto.getExpression() + " = " + dto.getResult();
@wlsh44 
`객체지향의 사실과 오해` 책에서 자주 말하는 내용 중에 하나가 이 부분과 관련되어 있는것 같아요 :) 
`다른 객체`로부터 `값`을 가져와서 `조합` 혹은 `변경` 하기 보다는 `댜른 객체`에게 `책임, 역할을 맡겨라` 라는 말을 많이 하는데요.

여기에서도 지금 dto를 통해 `get`을 여러번 호출하고 합치고 있는데 이 `역할`을 `dto`에게 맡기면 어떨까요?
그럼 다른곳에서 같은 기능이 필요하거나 수정이 필요할때 dto에게 맡기거나 수정할수 있겠죠 :)

2022-02-27 15:39 UTC, f-lab-mammouth commented on src/test/java/Calculator/CalculatorTest.java
> +        calculator = new Calculator(new SystemInputHandler(), new SystemOutputHandler(), new ArithmeticCalculateHandler(new DequeExpressionIterator()));
@wlsh44 
우선은 지금 하려는 테스트는 `unit test` 보다는 `integration test` 에 가까운것 같은데요.
`unit test`는 다른 클래스와 별개로 하나의 클래스로 테스트를 진행하는걸 말하고
`integration test`는 여러 클래스의 관계가 얽히는데 이런 관계를 가졌을때에 대한 테스트를 하는걸 말합니다.
한번 요 부분에 대해서 찾아보시길 바랍니다.

2022-02-27 15:44 UTC, f-lab-mammouth commented on src/test/java/Calculator/CalculatorTest.java
> +        calculator = new Calculator(new SystemInputHandler(), new SystemOutputHandler(), new ArithmeticCalculateHandler(new DequeExpressionIterator()));
@wlsh44 
해결책으로는 `Mock` 관련 library를 사용하는 방법이 있는데 요건 개인적으로 비추입니다.
다른 방법으로는 테스트용 `InputHandler`를 만드는겁니다.

지금 위 코드를 보면 `System.setIn(in)` 을 통해서 값을 넣어주고 `SystemInputHandler`에서 `inputData()` 메서드를 호출하여 `dto`를 생성하고 있는데, 테스트용 InputHandler를 만드는거죠.

1. test용 `InputHandler`를 만든다.
2. `initCalculator` 에서는 공통적으로 Calculator를 초기화 한다.
3. 이전에 말했던 `접근제어자`를 통해 test에서만 접근 가능한 `inputHandler`의 set 메서드를 사용한다.

2022-02-27 15:45 UTC, f-lab-mammouth commented on src/test/java/Calculator/CalculatorTest.java
> +    }
@wlsh44 
1번과 2번 테스트가 `input`과 `expect`만 달라지는거 같은데요.
`@ParameterizedTest`에 대해 찾아보세요.

항상 중복되는 부분을 줄이려고 생각하시면 답이 있습니다 :)

2022-02-28 16:32 UTC, wlsh44 commented on src/test/java/Calculator/CalculatorTest.java
> +        calculator = new Calculator(new SystemInputHandler(), new SystemOutputHandler(), new ArithmeticCalculateHandler(new DequeExpressionIterator()));
테스트용 `InputHandler`를 만들어서 코드를 변경하긴 했는데 멘토님께서 말씀하신 의도대로 된 건지는 잘 모르겠네요..
그리고 테스트용 `InputHandler`를 만들게 되면 `InputHandler`를 직접적으로 테스트하게 되는게 아니라 간접적으로 테스트 하게 되는 것 같아서 이 때문에 나중에 제대로 된 테스트를 못하게 될 수도 있지 않을까 하는 궁금증이 생겼습니다..!
또 `Mock`을 개인적으로 비추천 하시는 이유가 있으신가요?

2022-02-28 16:35 UTC, wlsh44 commented on src/main/java/Calculator/Calculator.java
> +        dto.setExpression(inputHandler.inputData());
`setter`를 없앤다는 것이 객체의 불변성을 의미하기 때문에 추후에 유지보수나 리팩토링을 할 때 더 안전하게 진행할 수 있다고 생각합니다!
그래서 `setter`를 없애기 위해  불가피하게 `CalculatorDto`를 쪼겠습니다.

2022-02-28 16:36 UTC, wlsh44 commented on src/test/java/Calculator/CalculatorTest.java
> +    }
`@ParameterizedTest` 형식으로 바꿨습니다.

2022-02-28 16:37 UTC, wlsh44 commented on src/main/java/Calculator/handler/IO/SystemOutputHandler.java
> +        String res = dto.getExpression() + " = " + dto.getResult();
`dto`의 `toString()`으로 출력 형식의 책임을 `dto`에게 넘겼습니다.

2022-03-01 14:11 UTC, f-lab-mammouth commented on src/main/java/Calculator/Calculator.java
> +        dto.setExpression(inputHandler.inputData());
@wlsh44 
지금 코드에서도 `dto.setExpression` 으로 넘겨주고 있는데 요고는 생성자로 바꿀수 없을까요?

2022-03-01 14:13 UTC, f-lab-mammouth commented on src/test/java/Calculator/CalculatorTest.java
> +        calculator = new Calculator(new SystemInputHandler(), new SystemOutputHandler(), new ArithmeticCalculateHandler(new DequeExpressionIterator()));
@wlsh44 
우선 여러 `mock` 라이브러리 들이 있습니다. 매우 편리하긴 하지만, 해당 라이브러리의 문법이나 사용법을 알아야 테스트를 이해할수 있는 단점이 있습니다. 팀에 사람이 많을수록 이런 부분이 걸림돌이 될수 있습니다. 
`정말 mock 라이브러리를 사용할수 밖에 없나?` 라는 질문을 해볼 필요가 있습니다. 객체지향적으로 잘 구현된다면 왠만한 상황에서는 `mock` 라이브러리 없이 테스트가 가능하다고 개인적으로 생각합니다 :)

2022-03-01 14:17 UTC, f-lab-mammouth commented on src/test/java/Calculator/CalculatorTest.java
> +        calculator = new Calculator(new SystemInputHandler(), new SystemOutputHandler(), new ArithmeticCalculateHandler(new DequeExpressionIterator()));
@wlsh44 
`InputHandler` 에 대해 의문을 가진건 정말 좋았습니다 :) 
제가 그렇게 하라고 해서 그냥 그렇게 구현하면 별로 도움이 되지 않을텐데, 계속 궁금증을 가지고 스스로 문제를 제기하는 모습 보기 좋습니다.
수정하신 코드는 말씀하신것처럼 `SystemInputHandler`를 테스트하는것과는 별개의 테스트가 됩니다. `SystemInputHandler` 와 `TestSystemInputHandler`가 같은 부모를 가지고는 있지만 두 클래스 간에는 관계가 형성되어 있지 않으니까요.

`SystemInputHandler`를 테스트하기 위해서는 그럼 어떻게 해야할까요? 
`SystemInputHandler`의 모든 기능과 속성을 다 가지고 있으면서 `좀 더 편하게 input을 넣어줄수 있는 메서드`만 하나 더 추가할수 있는 방법이 뭐가 있을까요?

2022-03-09 04:59 UTC, f-lab-mammouth commented on src/main/java/Calculator/handler/calculate/ArithmeticCalculateHandler.java
> +    }
@wlsh44 
`return (rightNum == 0) || (leftNum / rightNum != 0)` 로 해도 되지 않을까요?

2022-03-09 05:03 UTC, f-lab-mammouth commented on src/main/java/Calculator/handler/calculate/ArithmeticCalculateHandler.java
> +            if (operator.equals(Operator.DIVIDE) && isExceptionCase(leftNum, rightNum)) {
@wlsh44 
operator가 `null` 일경우 `NPE`가 발생할수 있어서 보통 이런 경우에는
`Operator.DIVIDE.equals(operator)` 과 같이 사용합니다 :)

2022-03-09 05:06 UTC, f-lab-mammouth commented on src/main/java/Calculator/util/CalculateUtil.java
> +    }
@wlsh44 
만약 새로운 `operator`가 생기면 `s.equals` 를 또 써줘야 하는데 좀 가독성이 많이 떨어지는 느낌인데요.
차라리 `Operator.symbol()` 들을 담고 있는 `Set`을 만들고 `Set`에 `String s`가 있는지 확인하는 방식으로 바꾸면 좀 더 깔끔할거 같아요 :)

2022-03-15 10:52 UTC, f-lab-mammouth commented
@wlsh44 
마지막 (6일전)에 드린 피드백들 수정해서 커밋하시면
`approve`로 상태 변경해드릴게요. 
그러면 최종 `merge` 하는것까지 진행해보시고 이 프로젝트는 종료하시면 될것같습니다 :)

2022-03-19 12:57 UTC, f-lab-mammouth approved these changes
수고하셨어요 👍 
`Approve` 로 상태 변경하겠습니다.
머징해주세요.

2022-03-20 07:58 UTC, merged